### PR TITLE
Sidebar

### PR DESCRIPTION
**Pull request by slobentanzer**
Several cosmetic changes and smaller adjustments

### CODE REVIEW

**Comment by slobentanzer** [comment]
@fengsh27 I reimplemented the changes I made, but I now encounter several bugs with core functionality. I don't know if it's a problem on my side, but I restarted and cleared my system a couple of times, rebuilt the Docker Compose, changed browsers, so it would be good if you could check (and also review the changes I made here).

Bugs I observe:
- conversations do not work (long "working" dots and then an empty response field after timeout)
- default values weird: 
    - the RAG checkbox in the chat should be off by default, but it's on
    - the mask splash screen should be off by default (in the settings, it is off), but it shows up when pressing "New Persona"; when it shows up, additionally there is no "never show again" button

**Comment by fengsh27** [comment]
@slobentanzer Sure, I'll have a look

**Comment by fengsh27** [comment]
@slobentanzer For the bugs:
 - Conversation issue, it worked on my side. This issue is probably due to api key issue. You can double check if, in rag settings page, it can connect to database. Without api key, it would fail to connect to database.
 - RAG checkbox issue, it worked on my side. To ensure the browser is initial state, we can delete local storage in "Developer Tools", refer to the following image.
 
image

 - Mask splash screen issue: I can reproduce it on my machine. I'll check why it doesn't work.

**Comment by fengsh27** [comment]
@slobentanzer I have made two submissions to show "Never show again" button. Would you please review them and confirm it is the desired effect.

**Comment by slobentanzer** [comment]
Thanks, will do. Actually received a new machine today, will set that up and use as a test bed for the technical issues, will update once I managed that.

**Comment by slobentanzer** [comment]
@fengsh27 on the new machine the response mechanism with GPT works again, I guess it was a settings or cache issue. :)

I think I figured out the problem with the RAG button on the bottom of the chat: it is connected to the "use RAG" button in the RAG settings. The way I envisioned it, these two are independent. The settings are global, used to manage the vector database, embedded docs, etc. The global setting should only be changed once when the user decides to use the feature. The button in the chat, on the other hand, is local, only activated if the user want one specific question supplemented by RAG (and same with KG). It should be off by default in every new chat, and basically an "opt-in" decision for every new question by the user. It could also be nice to automatically turn it off after the one question has been sent. This behaviour could be a global setting.

The "New Persona" splash screen changes are good, but now we go into a new blank conversation, which is not what we wanted. If the splash screen is turned off, the "New Persona" button should lead to the list-like selection (Persona overview) of different personas (the one that was previously in the chat menu bar).

Could you adjust these aspects?

**Comment by fengsh27** [comment]
> The "New Persona" splash screen changes are good, but now we go into a new blank conversation, which is not what we wanted. If the splash screen is turned off, the "New Persona" button should lead to the list-like selection (Persona overview) of different personas (the one that was previously in the chat menu bar). This was the button I think (so leading to `Path.Masks`):

Yes, I think I accomplish this quickly.

**Comment by fengsh27** [comment]
> I think I figured out the problem with the RAG button on the bottom of the chat: it is connected to the "use RAG" button in the RAG settings. The way I envisioned it, these two are independent. The settings are global, used to manage the vector database, embedded docs, etc. The global setting should only be changed once when the user decides to use the feature. The button in the chat, on the other hand, is local, only activated if the user want one specific question supplemented by RAG (and same with KG). It should be off by default in every new chat, and basically an "opt-in" decision for every new question by the user. It could also be nice to automatically turn it off after the one question has been sent. This behaviour could be a global setting.

@slobentanzer Let me clarify the usage of the "use RAG" settings, 
1. The global "use RAG" setting, found in RAG settings page, is specially used to control if users can upload documents and modify RAG settings like `chunk size`, `overlap size` and so on.
2. The local "use RAG" setting, found in chat, is used to determine if we should include RAG supplements as context.
These two settings are independent.
3. Optionally, we can provide a global setting that automatically turns off chat "use RAG" setting after each question.

Is this what we want to achieve?

**Comment by slobentanzer** [comment]
> Is this what we want to achieve?

@fengsh27 yes, correct

**Comment by fengsh27** [comment]
That's clear. It will take about 1-2 days to complete.

**Comment by fengsh27** [comment]
> > I think I figured out the problem with the RAG button on the bottom of the chat: it is connected to the "use RAG" button in the RAG settings. The way I envisioned it, these two are independent. The settings are global, used to manage the vector database, embedded docs, etc. The global setting should only be changed once when the user decides to use the feature. The button in the chat, on the other hand, is local, only activated if the user want one specific question supplemented by RAG (and same with KG). It should be off by default in every new chat, and basically an "opt-in" decision for every new question by the user. It could also be nice to automatically turn it off after the one question has been sent. This behaviour could be a global setting.
> 
> @slobentanzer Let me clarify the usage of the "use RAG" settings,
> 
> 1. The global "use RAG" setting, found in RAG settings page, is specially used to control if users can upload documents and modify RAG settings like `chunk size`, `overlap size` and so on.
> 2. The local "use RAG" setting, found in chat, is used to determine if we should include RAG supplements as context in conversation.
> 
> These two settings are independent.
> 
> 3. Optionally, we can provide a global setting that automatically turns off chat "use RAG" setting after each question.
> 
> Is this what we want to achieve?

@slobentanzer , 1, 2 have been implemented. Can you help to verify this is desired effect.

**Comment by slobentanzer** [comment]
@fengsh27 yes, seems to work fine now. There may still be some minor hiccups in the way the new conversations are started. E.g., the conversation that is initially created or the one that appears when you close all conversations in the history is still the plain "New Conversation"; this could maybe be replaced by one of the personas ("Plain Conversation"?).

But the RAG logic now works well; will merge this PR. Next up should be the integration of the BioChatter `RagAgent` as the main point of RAG interaction and extension to the KG query workflow through the same `RagAgent` class, right?

**Pull request merged**
