### PR TITLE
Implement RAG setting page

### PR DESCRIPTION
**Pull request by fengsh27**
### Abstract
This pull request implements the RAG modal dialog feature.

**chatgse-next:**
1. Added a RAG button to the chat action buttons, next to the model selection button. See the screenshot below:
   image
2. Implemented the RAG modal dialog with the following functionalities:
   - RAG settings ("use RAG", "chunk size", "overlap size", ...)
   - Uploading and removing RAG embedding documents. See the screenshot below:
     image
3. Enabled passing RAG config data to biochatter to enable injecting context.

**biochatter-server:**
Exposed the following interfaces:
- `/v1/rag/newdocument` (POST)
- `/v1/rag/alldocuments` (GET)
- `/v1/rag/document` (DELETE)
- For `/v1/chat/completions`, passed RAG config data to biochatter.

### Discussion
1. Considered implementing the documents selection feature, which allows users to select RAG documents for the current chat session from all uploaded RAG documents. However, this requires support from biochatter, which currently only supports similarity search from all documents. This may require minor efforts to implement.
2. Connection settings were not added in this submission. Since connection settings are more like global settings and the RAG config modal is chat session-based, it would be better to create a new task to add connection settings to the settings panel.
3. This submission did not implement the "last executed search: show the used fragments and their document metadata". I think we can to create a new task to track and implement this feature.

### CODE REVIEW

**Comment by slobentanzer** [comment]
Looks great, thanks! Will review ASAP

**Comment by slobentanzer** [comment]
Regarding the discussion:

> Considered implementing the documents selection feature, which allows users to select RAG documents for the current chat session from all uploaded RAG documents. However, this requires support from biochatter, which currently only supports similarity search from all documents. This may require minor efforts to implement.

1. is a good idea, but does not currently take high priority IMO. The main thing we want to show is that it is feasible, and I would ultimately like to have a sort of control centre for the vector DB anyways, where users could manage the DB (delete articles or collections, name them to keep different topics organised, things like that). We can make that a new issue.

> Connection settings were not added in this submission. Since connection settings are more like global settings and the RAG config modal is chat session-based, it would be better to create a new task to add connection settings to the settings panel.

2. agree on creating a new task, I think this should be possible fairly quickly and as such before paper submission. I am not sure how we will handle this in the online case, since in that case we need the users to provide a URL of their vector database. We can't feasibly host Milvus DBs for every individual user. Need to think about that, also how to handle it for the reviewers. Can we provide isolated instances of the app at specific URLs for each reviewer? That may be the simplest solution. @Wang-Cankun 

> This submission did not implement the "last executed search: show the used fragments and their document metadata". I think we can to create a new task to track and implement this feature.

3. Yes, this is very important for transparency. I will create a new issue and tag you.

**Comment by fengsh27** [comment]
> 2\. agree on creating a new task, I think this should be possible fairly quickly and as such before paper submission. I am not sure how we will handle this in the online case, since in that case we need the users to provide a URL of their vector database. We can't feasibly host Milvus DBs for every individual user. Need to think about that, also how to handle it for the reviewers. Can we provide isolated instances of the app at specific URLs for each reviewer? That may be the simplest solution. @Wang-Cankun

How about only displaying embedded documents uploaded in current chat session? Currently, all of embedded documents will be displayed and do similarity search? This requires that biochatter has the ability to do similarity search across selected documents.

**Comment by fengsh27** [comment]
> 2\. We can't feasibly host Milvus DBs for every individual user.

@slobentanzer  Are you referring to concerns about storage size?

**Comment by slobentanzer** [comment]
> Are you referring to concerns about storage size?

@fengsh27 No, more generally, do we host a vector DB, and how is storage managed. Will it be one Milvus instance that creates new collections for every user on the server?

**Comment by fengsh27** [comment]
@slobentanzer , I just mad a submission to support vector database settings in RAG.
image

After this submission, our strategy for vector database is like this:
1. vector database settings is ChatSession-based, that is, different ChatSession can work on different database.
2. if users don't specify database settings, they will work on the default vector database provided by us. The default database is shared among all ChatSessions which don't specify their own database. For the shared database, If necessary, we can ensure that each ChatSession only has access to the documents it has uploaded. This is achieved by frontend, which will save all documents id it uploaded. In vector database (biochatter), we won't create collections for each user.

**Comment by slobentanzer** [comment]
@fengsh27 this looks cool, good compromise between user-friendliness and complexity, at least in the short term. how persistent is the inventory of uploaded documents? I.e., if a user uses the default database, when does she lose the embedded documents, where are the IDs saved?

**Comment by fengsh27** [comment]
The document ids are saved in frontend (Local Storage). Currently, there are two ways for a user to lose embedded documents:
1. If users remove the embedded documents in RAG settings dialog. In this case, the corresponding embedded documents in database will also be removed.
image

2. If users deleted the chat session, all saved document ids will be lost. In this situation, we can remove embedded documents in database (not implemented yet).
image

**Comment by slobentanzer** [comment]
@fengsh27 thanks for clarifying. I think this is generally a good approach, but I am not sure the "chat session deletion" is intuitive. can we handle that on the global (session) level instead? e.g., what if the user wants to have several conversations about the same set of documents?

**Comment by slobentanzer** [comment]
@fengsh27 If the user runs from Docker compose, shouldn't the default IP for Milvus be `standalone`, according to the Docker network? `127.0.0.1` does not work for me when I run the docker compose, but `standalone` does.

**Comment by fengsh27** [comment]
@slobentanzer  Good question. I believe we can add an option called "upload globally (instead of in session)" in rag settings. This option would allow users to share documents globally. The global IDs would be stored globally in Local Storage, similar to app-config settings.
Moreover, we can add "embedded documents" to global settings page to allow users to manage these global documents.

**Comment by slobentanzer** [comment]
> add an option called "upload globally (instead of in session)" in rag settings

good idea. may be clearer if it is a toggle "Document availability" between "local (chat)" and "global (session)", or something else that is unambiguous.

> add "embedded documents" to global settings page

which global settings page do you mean?

**Comment by fengsh27** [comment]
image

I have circled the global settings button with a red pen, which will open the global settings page. And, I also circled the chat session settings button with a blue pen, which will open the session settings dialog.

**Comment by fengsh27** [comment]
@slobentanzer In global settings page, users have the ability to manage the global "Prompt List". I believe we can apply a similar approach to manage our global embedded documents.

**Comment by slobentanzer** [comment]
@fengsh27 thanks!

I see it like this: 
- the current RAG settings are more global than chat-specific, so the current page could go above the global settings button.
- related to #21, the chat could have a button that manages chat-specific RAG, such as turning the RAG on "per question/prompt"
- we could do the same (connection settings global, chat-specific activation) for the KG connectivity, essentially copying the layout of RAG with connection/auth settings and some information as in the ChatGSE Knowledge Graph tab.

> In global settings page, users have the ability to manage the global "Prompt List". I believe we can apply a similar approach to manage our global embedded documents.

Having a separate global RAG button would allow the same functionality and be clearer for the user, I believe.

Screenshot 2024-01-10 at 16 39 42

Thoughts?

**Comment by fengsh27** [comment]
Make more sense. This sounds clearer.

**Comment by fengsh27** [comment]
@slobentanzer Let me implement it.

**Comment by slobentanzer** [comment]
@fengsh27 running yarn I had an error and added some properties to the `dropzone` usage, please check if that is still fine on your side. https://github.com/biocypher/chatgse-next/pull/20/commits/a93c87b86a9028ff4db4267172841dc8a6f2a7f1

I am having the issue that the avatars are not rendered; I experimented with their definition in `en.ts`, but I can't get it to work. I just see empty spaces where they should be. Do you have an idea why that could be?

Screenshot 2024-01-11 at 10 28 02
Screenshot 2024-01-11 at 10 28 23

**Comment by slobentanzer** [comment]
@fengsh27 the last commit (https://github.com/biocypher/chatgse-next/pull/20/commits/e5d1ae9865fa7bb1907d3b82669ab433689310b0) adapts the docker compose to get the biochatter-server from dockerhub (biocypher has a sponsored org there). https://hub.docker.com/orgs/biocypher/repositories

I can also give you edit access to the dockerhub org, if you want to push newer server versions from the `biochatter-server` repo.

**Comment by fengsh27** [comment]
> I am having the issue that the avatars are not rendered; I experimented with their definition in `en.ts`, but I can't get it to work. I just see empty spaces where they should be. Do you have an idea why that could be?

@slobentanzer `emoji-picker-react` only supports emoji unified code. I added a converter to convert emoji to its unicode. Now, it works well.

**Comment by slobentanzer** [comment]
Plan sounds good, I merged the biochatter PR (bumped version to `0.3.11`).

**Comment by slobentanzer** [comment]
@fengsh27 Merged your new biochatter PR and bumped version to `0.3.12`.

Is the current version in this PR functional at the moment? When I try to embed a PDF (running in Docker Compose mode), the "Embedding and Saving" message pops up for a very short time, but then disappears again with no uploaded docs appearing in the list. I do see the new RAG button in the bottom right, so I'm pretty sure the frontend is current.

**Comment by fengsh27** [comment]
@slobentanzer Let me check what's wrong with it

**Comment by fengsh27** [comment]
@slobentanzer It works well to upload document on my end, but I fixed a bug when removing documents. I updated docker hub image biochatter-server:latest, can you please using this image to see if it resolves your issue.

**Comment by fengsh27** [comment]
@slobentanzer  Are you using Azure openai? When I switch to Azure OpenAI, I got this error message in biochatter-server:
 ```
UserWarning: If you have openai>=1.0.0 installed and are using Azure, please use the `AzureOpenAIEmbeddings` class.
```
I'll fix this issue.

**Comment by slobentanzer** [comment]
@fengsh27 works now, very nice! :)

is there anything you still want to do on this PR, or should we review/merge?

**Comment by fengsh27** [comment]
@slobentanzer  I'm working on biochatter repo to fix Azure OpenAI issue, and will raise a PR later. Once the biochatter PR is completed, I think we can update biochatter version and merge this PR.

What do you think?

**Comment by slobentanzer** [comment]
sounds good, will do

**Comment by fengsh27** [comment]
@slobentanzer The AzureOpenAIEmbeddings issue is more complicate than what I expected. I  think we can merge and complete this PR now, and I've created [an issue](https://github.com/biocypher/chatgse-next/issues/31) to track AzureOpenAIEmbeddings issus

**Comment by slobentanzer** [comment]
very good, will review now

**Comment by slobentanzer** [comment]
I added some cosmetics including the button changes we discussed, the KG button is just a copy of the RAG button that leads to an empty page for now.

**Review by slobentanzer — APPROVED** [review]
Seems like it could be a little buggy, it somehow got hung up trying to do RAG in Chrome, even after purging everything it still had a single conversation with a loading response. On Safari it worked, however, so I assume this is something that went wrong in my system. We'll have to look into CI to make sure that the components work, and also API documentation would be nice.

**Comment by fengsh27** [comment]
Agree, recently, we added to much code. We need more tests. 

By the way, I found only unit test is not enough, we also need like integration test. This time openai was upgraded to >=1.0.0, in biochatter, as our unit tests are all mocked, we can't find the incompatibilities in our code in time.

**Comment by slobentanzer** [comment]
@fengsh27 absolutely! I think we should prioritise CI updates as the next thing after the KG integration. Would you like to create an issue for that (or multiple), or should I?

**Comment by fengsh27** [comment]
@slobentanzer Certainly, I'll create an issue for CI test. If necessary, I'll break it down into multiple small issues.

**Comment by slobentanzer** [comment]
@fengsh27 somehow my cosmetic changes have disappeared. I have no idea what happened, I thought I had committed them to this PR as usual, but none of them are here. Will have to do again I fear. Will do on a dedicated branch this time. If you by chance find some cosmetic changes on your PR fork for this PR, let me know.

**Pull request merged**
